# Generated by Django 3.1.1 on 2020-10-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('all', 'all'), ('brand', 'brand'), ('img-mann', 'img-man'), ('creative', 'creative'), ('web', 'web'), ('print-mat', 'print-mat')], default='all', max_length=10),
        ),
    ]
